const reviews = [
    {
        name: "John Doe",
        comment: "Great quality and design!",
        star: 5,
        date: "2022-01-01",
    },
    {
        name: "Jane Smith",
        comment: "Not satisfied with the product.",
        star: 2,
        date: "2022-01-05",
    },
    {
        name: "Ann Smith",
        comment: "I love it!",
        star: 5,
        date: "2022-02-01",
    },
    {
        name: "Mark Johnson",
        comment: "Excellent customer service!",
        star: 4,
        date: "2022-02-15",
    },
    {
        name: "Emily Davis",
        comment: "Fast shipping and great packaging.",
        star: 5,
        date: "2022-03-01",
    },
    {
        name: "Michael Brown",
        comment: "The product exceeded my expectations.",
        star: 4,
        date: "2022-03-10",
    },
    {
        name: "Sarah Wilson",
        comment: "Good value for money.",
        star: 4,
        date: "2022-03-15",
    },
    {
        name: "David Lee",
        comment: "Impressive customer support!",
        star: 3,
        date: "2022-04-01",
    },
    {
        name: "Michelle Rodriguez",
        comment: "Highly recommended!",
        star: 5,
        date: "2022-04-10",
    },
    {
        name: "Robert Johnson",
        comment: "Great product, worth the price.",
        star: 4,
        date: "2022-04-15",
    },
    {
        name: "Maria Garcia",
        comment: "I love it!",
        star: 5,
        date: "2022-05-01",
    },
    {
        name: "William Smith",
        comment: "Impressive customer support!",
        star: 3,
        date: "2022-05-10",
    },
    {
        name: "Mary Smith",
        comment: "I love it!",
        star: 5,
        date: "2022-05-15",
    },
    {
        name: "James Smith",
        comment: "I love it!",
        star: 5,
        date: "2022-06-01",
    },
    {
        name: "Patricia Smith",
        comment: "Impressive customer support!",
        star: 5,
        date: "2022-06-10",
    },
    {
        name: "John Smith",
        comment: "I love it!",
        star: 5,
        date: "2022-06-15",
    },
    {
        name: "Robert Smith",
        comment: "Fast shipping and great packaging.",
        star: 3,
        date: "2022-07-01",
    },
    {
        name: "Jennifer Smith",
        comment: "I love it!",
        star: 5,
        date: "2022-07-10",
    },
    {
        name: "Michael Smith",
        comment: "I love it!",
        star: 1,
        date: "2022-07-15",
    },
    {
        name: "Linda Smith",
        comment: "I love it!",
        star: 5,
        date: "2022-08-01",
    },
    {
        name: "William Johnson",
        comment: "I love it!",
        star: 3,
        date: "2022-08-10",
    },
    {
        name: "Elizabeth Smith",
        comment: "I love it!",
        star: 3,
        date: "2022-08-15",
    },
    {
        name: "David Smith",
        comment: "I love it!",
        star: 5,
        date: "2022-09-01",
    },
    {
        name: "Barbara Smith",
        comment: "I love it!",
        star: 2,
        date: "2022-09-10",
    },
    {
        name: "Richard Smith",
        comment: "The product exceeded my expectations.",
        star: 5,
        date: "2022-09-15",
    },
    {
        name: "Joseph Smith",
        comment: "I love it!",
        star: 5,
        date: "2022-10-01",
    },
    {
        name: "Maria Smith",
        comment: "I love it!",
        star: 4,
        date: "2022-10-10",
    },
    {
        name: "Charles Smith",
        comment: "Not satisfied with the product.",
        star: 5,
        date: "2022-10-15",
    },
    {
        name: "Nancy Smith",
        comment: "The product exceeded my expectations.",
        star: 2,
        date: "2022-11-01",
    },
    {
        name: "Matthew Smith",
        comment: "I love it!",
        star: 5,
        date: "2022-11-10",
    },
    {
        name: "Susan Smith",
        comment: "Not satisfied with the product.",
        star: 3,
        date: "2022-11-15",
    },
    {
        name: "Anthony Smith",
        comment: "The product exceeded my expectations.",
        star: 2,
        date: "2022-12-01",
    },
    {
        name: "Karen Smith",
        comment: "Not satisfied with the product.",
        star: 1,
        date: "2022-12-10",
    },
    {
        name: "Karen Smith2",
        comment: "Not satisfied with the product.",
        star: 5,
        date: "2022-12-10",
    },
];

export default reviews;
